# docker-compose -p hivemq-test up -d
# https://hub.docker.com/r/hivemq/hivemq-ce
# https://github.com/hivemq/hivemq-community-edition#building-the-docker-image
# https://github.com/hivemq/hivemq-community-edition/wiki
version: '3.3'

services:
  primary:
    container_name: hivemq-test
    image: hivemq/hivemq-ce
    #deploy:
    #  restart_policy:
    #    condition: none
    #    max_attempts: 1
    ports:
      #Messaging
      - '1883:1883'
      #Messaging SSL
      - '8883:8883'
      #WebSocket
      - '8000:8000'
    