# docker-compose -p kafka-test up -d
# https://hub.docker.com/r/bitnami/kafka
# https://kafka.apache.org/
# https://github.com/confluentinc/confluent-kafka-dotnet

version: "2"

services:
  zookeeper-test:
    image: docker.io/bitnami/zookeeper:latest #3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-test:
    image: docker.io/bitnami/kafka:latest #3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-test

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local